graphql:
  playground:
    enabled: true
  graphiql:
    enabled: true
  servlet:
    exception-handlers-enabled: true
    tracing-enabled: true
    actuator-metrics: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics